### ISSUE TITLE
Show the correct passing of boolean values in the documentation

### ISSUE THREAD

**Issue by michamilz** [mkocansey/bladewind#103]
The bladewindui documentation shows passing of booloeans like this:
```
<x-bladewind.card has_shadow="false">
    // the card content goes here
</x-bladewind.card>
```

Following this results in a string. Using a string in `@if($has_shadow)` is always true. 
The correct way to pass booleans is:
```
<x-bladewind.card :has_shadow="false">
    // the card content goes here
</x-bladewind.card>
```

**Comment by mkocansey** [comment]
Hello @michamilz can you please confirm which version of BladewindUI you are reporting this for?
This was fixed in the latest version `v2.1.4` where ` has_shadow="false"` actually evaluates to false. 

All boolean attributes are now evaluated using `FILTER_VALIDATE_BOOLEAN`. 
For example  `$show_icon = filter_var($showIcon, FILTER_VALIDATE_BOOLEAN);` evaluates ` show_icon="false"` as a boolean

**Comment by michamilz** [comment]
Oh. I was using 2.1.2. Thanks for work.

**Comment by michamilz** [comment]
Sorry for reopening this issue :)

Your code evaluates the hasShadow attribute using `FILTER_VALIDATE_BOOLEAN`. The return value is assigned to `$has_shadow` variable.
 
```
$has_shadow = filter_var($hasShadow, FILTER_VALIDATE_BOOLEAN);
```

If i set the has_shadow attribute for the component in my blade file, the attribute will always be overwritten in the BladewindUI component by `true`.

**Comment by mkocansey** [comment]
@michamilz 
You are absolutely correct. Fixing now.

**Comment by mkocansey** [comment]
@michamilz kindly update to v2.1.6. Fixed in there
