### ISSUE TITLE
Label and Placeholder together on Input text box

### ISSUE THREAD

**Issue by kenwilliams5** [mkocansey/bladewind#27]
Currently, if you list a placeholder, even if it is blank, the label isn't displayed. On edit forms, if the field is blank, you still need to see the label to know what goes in that input box.

Love the way the label starts in the box as a placeholder and then moves to the label when the user enters the box, but why couldn't there be the label if we are editing and there is already something in the box?

I don't know if I'm making myself clear, but if you use the Placeholder attribute, the label won't show up at all.

**Comment by mkocansey** [comment]
@kenwilliams5 I think I understand you better now. The `label` attribute actually replaces `placeholder`. In most common cases input labels are displayed above the input box and don't interfere with the input's placeholder text. However, the Bladewind component's label is designed to sit in the same spot where the placeholder text is displayed and covers it up. 

Having a placeholder text that is longer than your label text results in some parts of the placeholder text sticking out under the label. To prevent this behaviour, the placeholder is hidden once a label is set. 

`<x-bladewind::input name="mobile" label="Mobile" placeholder="000.0000.000" selected_value="" />`

From above, in edit mode, the user will see the label _Mobile_ but will not know it is supposed to be in the format _000.0000.000_ because placeholder is ignored.

**Comment by kenwilliams5** [comment]
I understand, but is there any way to get both the label and placeholder to look like this for an edit screen?

![image](https://user-images.githubusercontent.com/26661990/171664334-46443987-72b8-47ff-b4ea-5dd4b2131042.png)

Or is placeholder the wrong attribute to use for a current value?

Maybe an enhancement would be to have the label show above if a placeholder or value attribute is defined?

**Comment by mkocansey** [comment]
An enhancement can definitely include this.. I'll add one more attribute for users who want to still show both placeholder and label.

**Comment by mkocansey** [comment]
@kenwilliams5 this enhancement is available in the latest version v1.0.2. Plead read the [docs here](https://bladewindui.com/component/textbox). Also, remember to publish assets again for changes to reflect. Let me know your thoughts when you try the enhancement out.

**Comment by kenwilliams5** [comment]
Thanks for the quick response and your efforts. I don't want you to think your efforts aren't appreciated!

I must be doing something wrong...I've tried several options and can't get it to work the way I would think it should.

When I try it like this:

```
<x-bladewind.input
                    name="fName"
                    :placeholder="$user->first_name"
                    :label="__('First Name')"
                    showPlaceholderAlways="true"
                    :selectedValue="$user->first_name"
                    wire:model.defer="user.first_name"
                    required="true"
                />
```
I get this when it does not have the focus:

![image](https://user-images.githubusercontent.com/26661990/171773085-1871473c-4012-4ec1-b025-f5ba995641e7.png)

When I move the focus to the element, I get this:

![image](https://user-images.githubusercontent.com/26661990/171773178-2a0fd525-2f38-4ba2-842d-296adbed2025.png)

which looks right, but the placeholder is actually just the placeholder and isn't editable. You have to type in everything you want to change it to. That's not a problem with MY name since it's so short, but if you had something longer and just wanted to change or insert/delete a few characters, you would have to type it all in again.

With this 

```
<x-bladewind.input
                    name="fName"
                    :label="__('First Name')"
                    :selectedValue="$user->first_name"
                    wire:model.defer="user.first_name"
                    required="true"
                />
```

it acts like there is no value supplied at all with the label as a placeholder until it gets focus, then the label moves up but there is nothing in the box. I would expect the selected value to be there.

I think the last version of the code is what I would expect to use and have the label be the placeholder only if the selected value is empty. If the selected value is not empty, I would expect the label to be up on top and the selected value be in the box and be editable. 

I don't know how you would handle any kind of placeholder that is used to show the proper format for a phone number or something like that when a selected value is present and not empty!!!

So let me know if I'm doing something wrong please!

Thanks again...

**Comment by kenwilliams5** [comment]
I've got it working the way I would like it to work...but you can't use the Livewire model attribute or this doesn't work!

I changed the bottom of the php code to:

```
    $placeholder_color = ($show_placeholder_always=='true' || $label == '') ? '' : 'placeholder-transparent';
    if($selected_value !== '') {
        $placeholder_label = '';
    } else {
        $placeholder_label = ($show_placeholder_always==='true') ? $placeholder : (($label !== '') ? $label : $placeholder);
    }
```

then changed my blade file to:

```
<x-bladewind.input
    name="fName"
    :label="__('First Name')"
    :selectedValue="$user->first_name"
    required="true"
/>
```

If the value of _selectedValue_ is empty, the placeholder is the label that goes to the top when the input gets focus. If it is NOT empty, the label is at the top and the value is in the input field where it is editable.

What do you think of that?

**Comment by mkocansey** [comment]
@kenwilliams5 What you described in your comment before the last is actually how the input component behaves. If there's a selected value the label jumps to the top and the text is editable. [Please check the example used in the docs](https://bladewindui.com/component/textbox) under **Default Values in Edit Mode**

Instead of `:selectedValue`, can you try `selectedValue` without the leading colon let's see if that works for you.

**Comment by kenwilliams5** [comment]
You are absolutely right!! I started a new project to try it without any other packages and it works like you described.

I think that when I had the Livewire stuff in there, it messed things up and I started editing before I realized it was causing problems.

Now, if I reinstall your package and publish it, it will get rid of all of my changes for the colors, sizes of text, etc. I guess doing a diff would be the only way to figure out what you changed and what I changed! Any suggestions?

**Comment by mkocansey** [comment]
The labels jumping into place and `selectedValue` being editable have been in the package since it launched. However the last change I did was to allow the placeholder text to still be displayed even if a label was set. Change was just to one file [in this commit](https://github.com/mkocansey/bladewind/commit/ea1796ecbaca446792bfbc2d1c5dbcc5967842df). The diff should help.
